openapi: 3.0.2
info:
  version: '1'
  title: 'Global API'
servers:
  - url: 'http://localhost:3000/api/global'
    description: Local environment
  - url: 'https://example.remote/api/global'
    description: Dev environment

paths:
  /state:
    get:
      operationId: listStates
      tags:
        - state
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
        - name: per_page
          in: query
          required: false
          schema:
            type: integer
        - name: search-name
          in: query
          required: false
          schema:
            type: string
          allowReserved: false    # <----query parameter that is not percent-encoded
      responses:
        '200':
          description: 'List of state models'
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/PaginationResult'
                properties:
                  Data:
                    type: array
                    items:
                      $ref: '#/components/schemas/State'
  /state/{id}:
    get:
      operationId: getState
      tags:
        - state
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 'Retrieve an state'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/State'
  
  /municipality:
    get:
      operationId: listMunicipalities
      tags:
        - municipality
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
        - name: per_page
          in: query
          required: false
          schema:
            type: integer
        - name: search-name
          in: query
          required: false
          schema:
            type: string
        - name: relationships
          in: query
          required: false
          schema:
            type: array
            items:
              type: string
              enum: ['state']
         
      responses:
        '200':
          description: 'List of municipality models'
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/PaginationResult'
                properties:
                  Data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Municipality'
  /municipality/{id}:
    get:
      operationId: getMunicipality
      tags:
        - municipality
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
        - name: relationships
          in: query
          required: false
          schema:
            type: array
            items:
              type: string
              enum: ['state']
      responses:
        '200':
          description: 'Retrieve an municipality'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Municipality'
  
components:
  schemas:
    State:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
      
    Municipality:
      type: object
      properties:
        id:
          type: integer
        idState:
          type: integer
        name:
          type: string

    Pagination:
      type: object
      properties:
        page:
          type: integer
        per_page:
          type: integer

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    
    ResourceReference:
      type: object
      properties:
        Name:
          type: string
        Action:
          type: string
        Ref:
          type: string
    
    PaginationResult:
      type: object
      properties:
        Links:
          type: object
          properties:
            next:
              $ref: '#/components/schemas/ResourceReference'
            current:
              $ref: '#/components/schemas/ResourceReference'
            prev:
              $ref: '#/components/schemas/ResourceReference'
        Page:
          type: integer
        Limit:
          type: integer
        Total:
          type: integer
